#!/usr/bin/env python3
"""Build SatSend's font-independent brand files (v1.5.5, roadmap v1.5.1-H).

The handoff logo SVGs (satsend-brand-handoff/assets) are *text* that needs Onest
installed, and they carry the old `.me` spacing (dx=-1.5). Email apps, PDFs and
favicons cannot load web fonts, so this script draws the wordmark from Onest's
real glyph outlines, shaped with HarfBuzz (kerning included), at the geometry of
src/components/brand/satsend-logo.tsx (the decided dx=1.5).

Outputs (paths relative to the repo root):
  public/brand/satsend-logo.svg             default (ink + amber .me)
  public/brand/satsend-logo-reversed.svg    for dark backgrounds
  public/brand/satsend-logo-monochrome.svg  single colour (currentColor)
  src/lib/brand/wordmark-paths.ts           path data for the PDF (react-pdf <Svg>)
The email PNG is rasterised from the default SVG by scripts/brand/raster-logo.mjs.

The PDF's fonts (src/lib/invoices/fonts/*.ttf) are NOT built here: they are
Google Fonts' own static files per weight (fonts.googleapis.com/css?family=
Onest:700 etc. → the fonts.gstatic.com .ttf), with the OFL licences alongside.

Usage (needs `pip install fonttools uharfbuzz` and the variable font from
github.com/google/fonts: ofl/onest/Onest[wght].ttf, saved as Onest.ttf):

    python3 scripts/brand/build-brand-assets.py <dir-containing-Onest.ttf>
"""
import os
import sys

import uharfbuzz as hb
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
INK, CANVAS, BRAND = "#151C2E", "#FCFBF7", "#D89B24"

# Geometry of src/components/brand/satsend-logo.tsx (keep in sync).
VIEWBOX = (0, 0, 420, 120)
X, BASELINE = 24, 82
RUNS = [
    # text, font-size, weight, letter-spacing, dx before the run
    ("SatSend", 72, 750, -4.3, 0.0),
    (".me", 42, 700, -1.4, 1.5),
]


def fmt(v: float) -> str:
    return f"{v:.2f}".rstrip("0").rstrip(".")


def shape_runs(onest_path: str):
    """Return [(path_d, run_index)] for each run, laid out like the SVG text."""
    blob = hb.Blob.from_file_path(onest_path)
    face = hb.Face(blob)
    upem = face.upem
    pen_x = X
    out = []
    for text, size, weight, spacing, dx in RUNS:
        font = hb.Font(face)
        font.set_variations({"wght": weight})
        buf = hb.Buffer()
        buf.add_str(text)
        buf.guess_segment_properties()
        hb.shape(font, buf, {"kern": True, "liga": True})
        tt = instantiateVariableFont(TTFont(onest_path), {"wght": weight})
        order = tt.getGlyphOrder()
        glyphs = tt.getGlyphSet()
        scale = size / upem
        pen_x += dx
        d = []
        for info, pos in zip(buf.glyph_infos, buf.glyph_positions):
            pen = SVGPathPen(glyphs, fmt)
            ox = pen_x + pos.x_offset * scale
            oy = BASELINE - pos.y_offset * scale
            glyphs[order[info.codepoint]].draw(TransformPen(pen, (scale, 0, 0, -scale, ox, oy)))
            d.append(pen.getCommands())
            # SVG letter-spacing is added after every glyph, including the last.
            pen_x += pos.x_advance * scale + spacing
        out.append("".join(d))
    return out


def svg(name_d: str, domain_d: str, name_fill: str, domain_fill: str, title: str) -> str:
    vb = " ".join(str(v) for v in VIEWBOX)
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{vb}" role="img" aria-label="SatSend">\n'
        f"  <title>{title}</title>\n"
        f'  <path fill="{name_fill}" d="{name_d}"/>\n'
        f'  <path fill="{domain_fill}" d="{domain_d}"/>\n'
        "</svg>\n"
    )


def write(rel: str, content, mode="w") -> None:
    path = os.path.join(ROOT, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, mode) as f:
        f.write(content)
    print("wrote", rel)


def main() -> None:
    src = sys.argv[1]
    onest = os.path.join(src, "Onest.ttf")

    name_d, domain_d = shape_runs(onest)
    write("public/brand/satsend-logo.svg", svg(name_d, domain_d, INK, BRAND, "SatSend.me"))
    write("public/brand/satsend-logo-reversed.svg", svg(name_d, domain_d, CANVAS, BRAND, "SatSend.me"))
    write(
        "public/brand/satsend-logo-monochrome.svg",
        svg(name_d, domain_d, "currentColor", "currentColor", "SatSend.me"),
    )
    write(
        "src/lib/brand/wordmark-paths.ts",
        "// GENERATED by scripts/brand/build-brand-assets.py — do not edit by hand.\n"
        "// The SatSend wordmark as Onest glyph outlines (decided .me spacing, dx=1.5),\n"
        "// for places that cannot load web fonts (the PDF).\n"
        f"export const WORDMARK_VIEWBOX = \"{' '.join(str(v) for v in VIEWBOX)}\";\n"
        f'export const WORDMARK_NAME_PATH = "{name_d}";\n'
        f'export const WORDMARK_DOMAIN_PATH = "{domain_d}";\n',
    )



if __name__ == "__main__":
    main()
